version: '3'
services:
  web:
    image: node:12-alpine
    tty: true
    container_name: ${PROJECT}-front
    volumes:
      - ./web:/src
    working_dir: '/src'
    ports:
      - '3001:3000'
    depends_on:
      - app
  app:
    build: .
    container_name: ${PROJECT}-api
    ports:
      - 80:80
      - 3000:3000
    volumes:
      - ./app:/var/www/html/${PROJECT}
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: ${PROJECT}-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${PROJECT}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql